package com.dsky.baas.ranklist.model;

public class LeaderBoardConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.leaderboardid
     *
     * @mbggenerated
     */
    private Integer leaderboardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.rank_cycle
     *
     * @mbggenerated
     */
    private String rankCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.expire_time
     *
     * @mbggenerated
     */
    private Integer expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.limit_rows
     *
     * @mbggenerated
     */
    private Integer limitRows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.sort_rule
     *
     * @mbggenerated
     */
    private String sortRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.redis_config
     *
     * @mbggenerated
     */
    private String redisConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.mysql_config
     *
     * @mbggenerated
     */
    private String mysqlConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_board_config.extend
     *
     * @mbggenerated
     */
    private String extend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.id
     *
     * @return the value of leader_board_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.id
     *
     * @param id the value for leader_board_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.game_id
     *
     * @return the value of leader_board_config.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.game_id
     *
     * @param gameId the value for leader_board_config.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.leaderboardid
     *
     * @return the value of leader_board_config.leaderboardid
     *
     * @mbggenerated
     */
    public Integer getLeaderboardid() {
        return leaderboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.leaderboardid
     *
     * @param leaderboardid the value for leader_board_config.leaderboardid
     *
     * @mbggenerated
     */
    public void setLeaderboardid(Integer leaderboardid) {
        this.leaderboardid = leaderboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.rank_cycle
     *
     * @return the value of leader_board_config.rank_cycle
     *
     * @mbggenerated
     */
    public String getRankCycle() {
        return rankCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.rank_cycle
     *
     * @param rankCycle the value for leader_board_config.rank_cycle
     *
     * @mbggenerated
     */
    public void setRankCycle(String rankCycle) {
        this.rankCycle = rankCycle == null ? null : rankCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.expire_time
     *
     * @return the value of leader_board_config.expire_time
     *
     * @mbggenerated
     */
    public Integer getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.expire_time
     *
     * @param expireTime the value for leader_board_config.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.limit_rows
     *
     * @return the value of leader_board_config.limit_rows
     *
     * @mbggenerated
     */
    public Integer getLimitRows() {
        return limitRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.limit_rows
     *
     * @param limitRows the value for leader_board_config.limit_rows
     *
     * @mbggenerated
     */
    public void setLimitRows(Integer limitRows) {
        this.limitRows = limitRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.sort_rule
     *
     * @return the value of leader_board_config.sort_rule
     *
     * @mbggenerated
     */
    public String getSortRule() {
        return sortRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.sort_rule
     *
     * @param sortRule the value for leader_board_config.sort_rule
     *
     * @mbggenerated
     */
    public void setSortRule(String sortRule) {
        this.sortRule = sortRule == null ? null : sortRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.redis_config
     *
     * @return the value of leader_board_config.redis_config
     *
     * @mbggenerated
     */
    public String getRedisConfig() {
        return redisConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.redis_config
     *
     * @param redisConfig the value for leader_board_config.redis_config
     *
     * @mbggenerated
     */
    public void setRedisConfig(String redisConfig) {
        this.redisConfig = redisConfig == null ? null : redisConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.mysql_config
     *
     * @return the value of leader_board_config.mysql_config
     *
     * @mbggenerated
     */
    public String getMysqlConfig() {
        return mysqlConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.mysql_config
     *
     * @param mysqlConfig the value for leader_board_config.mysql_config
     *
     * @mbggenerated
     */
    public void setMysqlConfig(String mysqlConfig) {
        this.mysqlConfig = mysqlConfig == null ? null : mysqlConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.create_time
     *
     * @return the value of leader_board_config.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.create_time
     *
     * @param createTime the value for leader_board_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_board_config.extend
     *
     * @return the value of leader_board_config.extend
     *
     * @mbggenerated
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_board_config.extend
     *
     * @param extend the value for leader_board_config.extend
     *
     * @mbggenerated
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }
}